apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-random
  namespace: mvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-random
  template:
    metadata:
      labels:
        app: book-random
    spec:
      containers:
      - name: app
        image: ubuntu
        env:
        - name: BOOK_URL
          value: https://www.gutenberg.org/files/2701/2701-0.txt
        command:
        - /bin/bash
        - -c
        - |
          apt-get -y update && apt-get -y install wget
          wget $BOOK_URL -O /root/book.txt
          i=0; while true; do
            line=$(shuf -n 1 /root/book.txt)
            mysha=$(echo $line | sha1sum)
            echo "$mysha $i $line"; i=$((i+1))
            sleep 10
          done
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 800m
            memory: 500Mi